### PR TITLE
Gradio #259 Search stations by tag

### PR DESCRIPTION
**Pull request by erwinvaneijk**
I've implemented search by tags with a completion feature on a text entry box. That works reasonably well so far.

### CODE REVIEW

**Comment by haecker-felix** [comment]
Sorry for the delayed answer. I just tested it. It works fine! I think this is a nice solution, maybe I'm going to implement this also for the other groups like language. I think it's a lot easier to enter/search for a entry, instead of scrolling through a big list of items.

**Comment by erwinvaneijk** [comment]
No problem. I've done this for tags, because it was new and I got the feeling that it'd be good for language and country as well. If you don't mind I'll change the other options like this tomorrow...

**Comment by haecker-felix** [comment]
You don't need to do this. I'm currently working on it. I'm changing some things on the design of the filter popover.

Your work would be useless. But thanks for the offer. Feel free to improve something else :stuck_out_tongue:

**Comment by erwinvaneijk** [comment]
Ok, that's okay. Anything in particular you'd like me to put some effort towards?

**Comment by haecker-felix** [comment]
#261 might be interesting. I'm not sure how I should realise this. Maybe with with a tag over the station icon? I don't know...

Maybe you have a idea. But please talk to me first, if you are planning to do something bigger.

I think it's a stupid idea to include the bitrate information in the station title, it's a place where it shouldn't be.

**Comment by haecker-felix** [comment]
FYI: The new filter popover is now on master. I think it's waaay better than the old one.

**Comment by erwinvaneijk** [comment]
Yes, it looks much better!

 Although I feel that the user experience can be improved by changing the buttons that say 'change language' etc, to the 'greyed out default text in a text entry'. But I can't quite find how you can do that.

**Pull request merged**
