### PR TITLE
Add notifications, tray and new tag

### PR DESCRIPTION
**Pull request by kajzersoze**
First I just want to say that I love this app, great job !

Now, I've added few things that I was missing, like tray option and closing to tray, there is a option to turn that feature off, in tray itself on right click there are options to Play / Pause and Quit. Left click will bring the main window back if it was closed to tray.
Second thing is notifications when station change to a new song.
Third thing is a new TAG , some stations provide url for the art from the front cover of the album that is playing in homepage TAG, example of that is in the attached picture, station is Radio Paradise.
If there's no art in that TAG then standard station icon will show instead.

Also, you forgot to load window positions from gsettings, so that's added as well :)

untitled

### CODE REVIEW

**Comment by haecker-felix** [comment]
Thanks for your work. Currently I'm in holiday. I'll look at your code in the next two weeks.

**Comment by haecker-felix** [comment]
Very useful! There are several little things I have to change (like opt-in for "Close to tray" instead of opt-out), but thanks for your work!

This fixed #28

**Comment by kajzersoze** [comment]
Sure, that's a good idea, you might also want to add "Show notifications" in Settings and make that optional as well, I forgot to add that.

**Comment by haecker-felix** [comment]
Yes yes. No problem. That are small things.

**Pull request merged**
