### PR TITLE
add AUR package

### PR DESCRIPTION
**Pull request by bil-elmoussaoui**
I've created an AUR package(Arch) for gradio, the package will build the latest git version. I can add a stable release too if you can create releases on Github. 
The package link : https://aur.archlinux.org/packages/gradio-git/
If you think there's something i should change on the package information, don't hesitate :)

### CODE REVIEW

**Comment by haecker-felix** [comment]
Thanks! I'll release a stable release soon.

**Comment by bil-elmoussaoui** [comment]
Can you ping me once its done ?

**Comment by haecker-felix** [comment]
@bil-elmoussaoui yes. no problem.

**Comment by haecker-felix** [comment]
@bil-elmoussaoui for more information see:

https://github.com/haecker-felix/gradio/milestones

**Comment by haecker-felix** [comment]
@bil-elmoussaoui gradio 4.0 is here. This _should_ be a stable release.

**Pull request merged**
