### PR TITLE
Deprecated code replaced and unused variables deleted

### PR DESCRIPTION
**Pull request by mohamedsakhri**
More info about async here: http://i-hate-farms.github.io/campfire/tutorials/async-and-threading.html

### CODE REVIEW

**Comment by haecker-felix** [comment]
I know how to use async (and yes i know this website ^^). Many parts of gradio (for example the station-provider class) use threads and async.

But does gradio runs so faster / smoother with the async sidebar categories? Because we need this method only one time (startup).

**Comment by mohamedsakhri** [comment]
The first commit replaced a deprecated code. You can see the warning during compiling. I cannot confirm that Gradio runs much faster because that requires benchmarking. But usually running a task in a new thread increases it chances to get executed faster.

**Comment by haecker-felix** [comment]
Yes a _chance_. I also have tried this, but undo it because there were no significant speed improvements. 
But is's okay. 

Thanks for your cleanup ;)

**Comment by mohamedsakhri** [comment]
You are welcome :)

BTW, is there a reason why did you change the settings' window? I think the old one was smoother and looks modern.. ;)

**Comment by haecker-felix** [comment]
Mhm. I think the new is more structured and more logical. I like the new one more ^^.

What exactly was better on the old one? The (gtk)switches? Say it. Maybe i can improve the new one :)

**Comment by mohamedsakhri** [comment]
The new one is more structured, I agree. But I like the old design more. Maybe you can combine the new structure with the old design by using switches instead of the radio-buttons and another design for the tabs. Here is an example (It's from Plank dock):

plank_003

**Comment by mohamedsakhri** [comment]
And you already have the same design for the tabs "Library" and "Discover" ;-)

**Comment by haecker-felix** [comment]
Ah I know what do you mean.

**Comment by haecker-felix** [comment]
Done.

**Comment by mohamedsakhri** [comment]
They look much better, don't they?
Are you planing to change the checkboxes/radio-buttons to gtk-switches too?

**Comment by haecker-felix** [comment]
Yes the tabs look better. 

Idk. The switches are alwas to big. The checkboxes are easier to use, for me. (my opinion)

**Comment by haecker-felix** [comment]
I'm sorry, but i have to remove the async parts. It is not threadsafe. Gradio does random crash now.

**Comment by mohamedsakhri** [comment]
Go ahead, it's okay. You know better than me in UI and gtk :)

**Comment by haecker-felix** [comment]
I just wanted to say. (before you think I i'm a asshole and delete your work ^^)

**Comment by mohamedsakhri** [comment]
:+1: 

I read this [article about checkboxes and switches](https://elementary.io/docs/human-interface-guidelines#checkboxes-switches). It's hard to tell which ones suite the gradio's settings the best. Some settings are like a "on/off" settings and others are like a list (e.g discover categories).

**Comment by haecker-felix** [comment]
If you believe me or not, i've read this document. I couldn't decide. After that i just looked, how the nautilus settings window is done. 

As I already said: The switches are too big :/

**Comment by mohamedsakhri** [comment]
We are following the same path because I looked at the nemo's settings, which is a fork from nautilus under Linux Mint :D 
I now also think that sticking with checkboxes is the right thing :+1:

**Comment by haecker-felix** [comment]
Haha okay :D

**Comment by mohamedsakhri** [comment]
I have a question and a suggestion which are not so important to to open new issues for, so I'm just writing them here :)

**Question**:  the stations in Library are sorted according to which criteria? It doesn't seem to be alphabetically. I couldn't figure out how they are sorted.

**Suggestion:**  The "**...**" to load more stations at the bottom of the discovery window doesn't seem to be visible/noticeable enough. I've just pay attention to it today! Maybe an icon or "Load more" would be better?

**Comment by haecker-felix** [comment]
Question: Idk... Ask the GLib.HashMap :see_no_evil: 
Suggestion: Wait 2 min.

**Comment by mohamedsakhri** [comment]
:smile: 
I got your last commit :) I actually was talking about this:

gradio_001

**Comment by haecker-felix** [comment]
Oops. 

Btw: Your sidebar looks horrible. Why you don't say anything... The buttons should have the same color as the sidebar....

**Comment by mohamedsakhri** [comment]
I wasn't sure if my sidebar looks bad because of my GTK+ and theme, because I saw yours on the `Readme.md` and it looks good. That's why I didn't report that.

The "more .." is better now. However I think the buttons on the right of "most popular" etc. and those at the bottom should be different.

**My suggestion** would be a styled arrow ">" for the buttons on top and a styled arrow (v) on the bottom with the text "load more".
Here is an example from google:
google

**Comment by haecker-felix** [comment]
I've tried some other gtk themes, but i cannot reproduce this "ugly". 

Suggestion accepted :+1: . Check the latest commit.

**Comment by mohamedsakhri** [comment]
Maybe because I'm using XFCE, which is an "old school" DE ;-)

Thanks for the quick response to my suggestion :+1:  You only changed the buttons on top though :wink:

**Comment by mohamedsakhri** [comment]
After the last commit Gradio is taking too much time to start! Here is the output from the terminal:

```
** Message: gradio.vala:176: Starting Gradio version 5.0.0b2!
** Message: gradio.vala:36: No existing window, starting new session.
** Message: settings.vala:24: Loaded settings module
** Message: library.vala:111: Reading library data from: /**/.local/share/gradio/library.gradio
** Message: library.vala:136: Successfully imported library

(gradio:20969): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(gradio:20969): GLib-GObject-CRITICAL **: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(gradio:20969): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(gradio:20969): GLib-GObject-CRITICAL **: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
** Message: main-window.vala:75: Desktop session is: xfce
** Message: category-item-provider.vala:36: Fetching category items...
** Message: radio-station-provider.vala:101: Requested results from 0 to 10
** Message: radio-station-provider.vala:101: Requested results from 0 to 10
** Message: radio-station-provider.vala:101: Requested results from 0 to 10
** Message: utils.vala:96: Loaded CSS from: /usr/local/share/gradio/gradio.css
** Message: mpris.vala:65: name acquired

** Message: category-item-provider.vala:127: Successfully loaded category items!
** Message: stations-view.vala:174: Results_loaded: 10

** Message: stations-view.vala:175: max_results: 6166

** Message: discover-box-sidebar.vala:139: Loading category items...
** Message: stations-view.vala:174: Results_loaded: 10

** Message: stations-view.vala:175: max_results: 6166

** Message: stations-view.vala:174: Results_loaded: 10

** Message: stations-view.vala:175: max_results: 6166

** Message: radio-station.vala:86: Playable url: http://hr-mp3-m-h1.akacast.akamaistream.net/7/783/142131/v1/gnl.akacast.akamaistream.net/hr-mp3-m-h1

```

**Comment by haecker-felix** [comment]
Fixed.

**Comment by mohamedsakhri** [comment]
:+1: 

I have another idea for the design of the "more..." button. I'll try to make it as a mockup first and send it to you :)

**Comment by haecker-felix** [comment]
Now I'm curious :)

**Comment by mohamedsakhri** [comment]
Here we go :smiley: 
1. Show more in the discovery window
more-mockup

2. Load more stations after search by country etc.:
load-more-mockup

BTW: If you are still looking for an icon set you can take a look at [the material design icons](https://materialdesignicons.com/)

**Comment by haecker-felix** [comment]
On the first picture: What I have to click? The arrow or the text?

**Comment by mohamedsakhri** [comment]
It's the arrow which should be clicked. But after seeing the picture many times and the discover window, I'm not sure about this idea.. It feels like too much text and icons in a small place.

I'm living in Germany :de:

**Comment by mohamedsakhri** [comment]
@haecker-felix Have you thought about using [Travis CI](https://travis-ci.org/)? It's a nice tool to build your App automatically and than get a feedback after every commit or pull request..

**Comment by haecker-felix** [comment]
Servus :de: :smiley: 

Travis use ubuntu 14.04 as build env, which is too old for gradio. GTK is too old (3.10) and some webkits packages are missing. It would be possible to get newer packages from PPAs, but this is too much work for now. 

------------------------------------------------------------------------------------------------------
Worker information
hostname: travis-worker-gce-org-prod5-9:11cc6778-8eb9-40ed-83fd-4fbefd94689e
version: v2.3.1-34-g4ab376b https://github.com/travis-ci/worker/tree/4ab376ba587e12cb465474238c78e88e6600aca2
instance: testing-gce-6da24294-9cb4-480c-80d2-37cc04e01501:travis-ci-sugilite-trusty-1471824869
startup: 21.780822234s
system_info
Build system information
Build language: c
Build group: stable
Build dist: trusty
Build id: 171740409
Job id: 171740410
travis-build version: f2e5e21fe
Build image provisioning date and time
Mon Aug 22 00:52:43 UTC 2016
Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.4 LTS
Release:	14.04
Codename:	trusty
Linux Version
3.19.0-64-generic

...

sudo apt-get install -qq gnome-common gobject-introspection libwebkit2gtk-4.0-dev build-essential valac cmake glib2.0 gtk+3.0 gstreamer1.0 libjson-glib-dev libsoup2.4
E: Unable to locate package libwebkit2gtk-4.0-dev
E: Couldn't find any package by regex 'libwebkit2gtk-4.0-dev'

The command "sudo apt-get install -qq gnome-common gobject-introspection libwebkit2gtk-4.0-dev build-essential valac cmake glib2.0 gtk+3.0 gstreamer1.0 libjson-glib-dev libsoup2.4" failed and exited with 100 during .

Your build has been stopped.

**Pull request merged**
